.PHONY : all clean
all : 1x1conv_layer 3x3conv_layer
1x1conv_layer : 1x1conv_layer.c
	gcc -o 1x1conv_layer 1x1conv_layer.c
3x3conv_layer : 3x3conv_layer.c
	gcc -o 3x3conv_layer 3x3conv_layer.c
clean :
	rm 1x1conv_layer 3x3conv_layer


